#!/bin/sh
set -e

cd ~/.vim_runtime

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry' > ~/.vimrc

if [ ! -d "${HOME}/.vim_runtime/my_plugins/fzf" ]; then
    git clone --depth=1 https://github.com/junegunn/fzf.git ~/.vim_runtime/my_plugins/fzf
    git clone --depth=1 https://github.com/junegunn/fzf.vim.git ~/.vim_runtime/my_plugins/fzf.vim
fi

echo "Tmux setup, please make sure tmux already installed"
cp ~/.vim_runtime/tmuxs/tmux.conf ~/.tmux.conf

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
